### ISSUE TITLE
Heuristics for when to use certain schemes?

### ISSUE THREAD

**Issue by ataber** [nschloe/quadpy#146]
Hi, thanks for the great package!

Are there any resources for those of us who are looking to play around with different rules without diving deep into the literature? I don't understand the distinctions between many of the formulae (except of course the salient parts like order), and I'm not sure how to learn the distinction without combing through the original papers. Thanks!

**Comment by nschloe** [comment]
There's the order of course, and two other important criteria:

  * Are all points inside the comain, or may points be on the boundary or outside?
  * Are all weights positive?

(Well, the importance depends on your application. If you can evaluate your functions everywhere anyways, you're fine with anything in the first criterion.)

Both of the above things can be checked easily when simply looking at the weights and points, but yeah, that's something you'll have to do manually.

I'm not quite sure what a "scheme selector" could do, so that's why there is none.

**Comment by ataber** [comment]
I'm also not sure what a scheme selector would do :)

Are there certain non-obvious features of various rules that may be useful in certain situations? I'm thinking things like symmetry of point distribution, or maybe a rule that works particularly well with certain integrands for instance.

This isn't really related to this software in particular (though it could be seen as documentation-related), so I totally understand if you want to close this issue. Thanks!

**Comment by nschloe** [comment]
> Are there certain non-obvious features of various rules that may be useful in certain situations? I'm thinking things like symmetry of point distribution,

None that I know of. Symmetry is of course a nice feature, but really if you care about the result of the integration it might not be tremendously important to you. Ultimately, you'll always have to take a second and look at the scheme. quadpy should make that easy too:
```python
import quadpy
quadpy.triangle.show(quadpy.triangle.Dunavant(10))
```
