### ISSUE TITLE
classes -> functions?

### ISSUE THREAD

**Issue by nschloe** [nschloe/quadpy#153]
All quadrature scheme classes do nothing else than setting the data in `__init__`. Would we lose anything when converting all classes to functions that return the respective scheme?

**Comment by burnpanck** [comment]
On the other hand, what would you gain? You would still need some object or container to hold the parameters that you output from the factory function. I find it actually rather elegant to have the type of that object indicate what the parameters assigned to it (in it's `__init__`) encode what the object actually represents. This way, the object conveys additional meaning, e.g. that you can expect an `order` attribute which describes the integration order.
I would rather see it the other way around: The scheme is an object to perform integration - it should expose a method doing that integration. Since that method internally actually always looks the same for the same type of domain it would probably be implemented in a base-class. Of course, for people expecting a functional interface, one would still preserve top-level functional wrappers around that integration function. The classes could then offer further methods, such as error estimations or order selection helpers - some of which might be generic on the domain, others specific to the scheme.

**Comment by nschloe** [comment]
You're right. As of quadpy 0.13.0, all schemes will be accessible via generator functions; the schemes are objects on which you can call `integrate()`, `citation`, `show()`, etc.

**Comment by zerothi** [comment]
Possibly one could add `__call__` to all classes with arguments overwriting object variables. In that way it works like a method and a class?
