### ISSUE TITLE
Integral calculation result is not correct.

### ISSUE THREAD

**Issue by Nochenon** [nschloe/quadpy#172]
```python
print(quadpy.line_segment.integrate(lambda x: scipy.exp(1j*x), [-1, 100],quadpy.line_segment.GaussKronrod(3)))
```
The code is for calculating integral of exp(j*x) from -1 to 100, however, it returned a wrong value:
```
(-11.219936196799733+10.78170013544869j)
```

According to wolframalpha, the result should be:
```
(0.335105 - 0.322017j)
```
But the result of the code provided by Nico Schlömer in stackoverflow is correct:
```
val = quadpy.line_segment.integrate(
        lambda x: scipy.exp(1j*x),
        [0, 1],
        quadpy.line_segment.GaussKronrod(3)
        )
print(val)
```
result:
```
(0.841470984808+0.459697694132j)
```
Am I missing something?

**Comment by nschloe** [comment]
If you integrate `exp(1j*x)` over a small interval, say `[-1, 2]`, the function looks fairly smooth and can be approximated well by polynomials of low degree. That's why the quadrature (which is an approximation, remember!) with GaussKronrod(3) gives good results.

Making the interval really large, `[-1, 100]`, it can no longer be approximated well by low-degree polynomials which is why GaussKronrod(3) gives a very inaccurate result.

Note that you can use `integrate_adaptive` (which uses Gauss-Kronrod internally) to get a better result:
```
import quadpy
import scipy

val, err = quadpy.line_segment.integrate_adaptive(
    lambda x: scipy.exp(1j*x), [-1, 100], 1.0e-10
    )

print(val)
```
```
(0.3351053436984601-0.3220165664198509j)
```
