### ISSUE TITLE
`quad` bad results example

### ISSUE THREAD

**Issue by OverLordGoldDragon** [nschloe/quadpy#390]
In application `scipy.integrate.quad` gives more sensible results; full example below. For whatever reason a narrow range of function behaviors doesn't integrate well. Using v0.16.3.

<details>
    <summary>Code</summary>

```python
import numpy as np
import matplotlib.pyplot as plt

from quadpy import quad as quadgk
from scipy import integrate

#%%##########################################################################
def morlet(mu=6.):
    cs = (1 + np.exp(-mu**2) - 2 * np.exp(-3/4 * mu**2)) ** (-.5)
    ks = np.exp(-.5 * mu**2)
    return lambda w: cs * np.pi**(-1/4) * (np.exp(-.5 * (mu - w)**2)
                                           - ks * np.exp(-.5 * w**2))


def compare(mu):
    psihfn = morlet(mu)
    intfn = lambda w: np.conj(psihfn(np.asarray(w))) / w
    
    out1 = quadgk(intfn, 0., np.inf)[0]
    out2 = integrate.quad(intfn, 0., np.inf)[0]
    return abs(out1 - out2), out1, out2

#%%##########################################################################
diffs = []
for mu in np.linspace(4, 24, 200):
    diffs.append(compare(mu)[0])
    if diffs[-1] > .01:
        print(mu, diffs[-1])
diffs = np.array(diffs)

plt.hist(diffs, bins=500)
plt.show()
print("min: {:.4e}, max: {:.4e}, mean: {:.4e}".format(
    diffs.min(), diffs.max(), diffs.mean()))
#%%
print("mu=20:\nquadpy: {:.4e}\nscipy: {:.4e}".format(*compare(20)[1:]))
```

</details>

**Comment by nschloe** [comment]
You can simplify this example a lot more. Consider
```python
import numpy as np

import quadpy
from scipy import integrate

def f(x):
    return np.exp(-0.5 * (20.0 - x) ** 2) / x


out1, err1 = quadpy.quad(f, 0.0, np.inf)
print(out1, err1)
out2, err2 = integrate.quad(f, 0.0, np.inf)
print(out2, err2)
```
```
6.110645390743225e-09 5.9060754349291706e-09
0.12564712213038612 6.403496171204715e-09
```
Indeed, scipy and quadpy spit out different results. It's now easy to see why: The function you're trying to integrate is as a non-integrable pole at 0! None of the results will have any meaning. If you start your integration at 0.2, for example, you'll get
```
0.12564712210594048 4.523133377642496e-10
0.12564712213038612 1.048383372858511e-08
```
Looks better.

**Comment by OverLordGoldDragon** [comment]
Not really non-integrable; the function has a [well-defined limit at zero](https://www.desmos.com/calculator/0sqcx2cwiv). True quadpy fixes itself at .2, but why not at .1, or 1e-10? Further, quadpy struggles to handle your simplification for smaller `mu`, while scipy doesn't. I tried increasing `limit` for both (scipy doesn't demand it but informs of possible inaccuracy), and scipy handled it swiftly while quadpy ate 20GB of RAM and didn't get far.

I've never coded numeric integration so maybe there's really something at 0 but the rest of points stand; worst-case scipy handles non-integrability intelligently. And btw the limit's also well-defined numerically:

```python
t = np.linspace(-2, 24, 26001)
plt.plot(t, psihfn(t))
print(0 in t)
```

scipy's results are also meaningful in context, which is signal reconstruction, yielding accurate amplitude (easily verified).

**Comment by nschloe** [comment]
> Not really non-integrable; the function has a well-defined limit at zero.

That's not true. You have a pole at 0 that you don't see in the plot because the resolution is too coarse. The function
```
def f(x):
    return np.exp(-0.5 * (20.0 - x) ** 2)  # without / x
```
has some (very small) value around 0. Then you divide that value by `x` and you get a non-integrable pole. Granted it's weird because it's something like `1e-87 / x`, but here's your problem.

**Comment by OverLordGoldDragon** [comment]
Alright, I was [wrong](https://www.wolframalpha.com/input/?i=limit+exp%28%28x-6%29%5E2%29+%2F+x+as+x+-%3E+0) regarding the limit. Further I found that scipy also messes up for `mu` around 21 to 22, even if setting lower bound to 1 - so we basically have a bunch of unstable behavior that needs manual handling:

<img src="https://user-images.githubusercontent.com/16495490/100097818-86f2a680-2e76-11eb-967b-8612370755db.png" width="400">

Still I'm unsure why even 1 to inf isn't good enough when there's no unstable behavior there; I've also tried 1 to inf with `limit=int(1e9)` for both (quadpy didn't devour RAM this time); only higher lower limit fixes it. Is there a method/option that better handles this case (besides ramping up lower limit)?

**Comment by nschloe** [comment]
> Alright, I was wrong regarding the limit.

It's not only the fact that there's a limit. There are integrable poles, too, for example `1 / sqrt(x)`. `1 / x` isn't one of them though.

> scipy's results are also meaningful in context, which is signal reconstruction, yielding accurate amplitude (easily verified).

This could be merely a coincidence. I'd be _very_ careful here. The problem is that your integral value is undefined (or infinity), and it's only due to the numerical shortcomings of scipy that you get some value. The value is _wrong_, and could as well be arbitrary.

If I were you, I'd check my math. If something is that wrong, chances are there's a mistake in there.

**Comment by OverLordGoldDragon** [comment]
Right, the math does confirm that the function is a bad _strict_ integration candidate starting at 0, but still starting at `.1` or so shouldn't be troublesome but is. I still don't follow why `2` accomplishes what `1` doesn't as a lower bound candidate, but both libraries suffer this so guess `quadpy` is fine here. Still is there another integration scheme that doesn't demand not only exclusion of the pole but also being quite far away from it?

**Comment by OverLordGoldDragon** [comment]
In fact `2` doesn't do it either - it just shifts the "dip" in the above plot vs mu. If I keep increasing lower bound then integration is very inaccurate for small mu, but no dips. And why even a "dip" - if things go bad after some mu, shouldn't they _stay_ bad? I'm asking too many questions at this point but I'll just leave the note about `2`.

**Comment by nschloe** [comment]
Perhaps it's useful for you to know what adaptive integration does: At its core, there an ordinary Gauss-Kronrod integration that, given a function and a finite interval, gives a value plus an error estimate. If the estimate is "too large", the interval is split (mostly in two). The same thing is repeated for each of the parts until all subintervals have low-enough error estimates, and then the value estimates are summed up.

You can imagine what happens if there is a pole: The method will produce a large error estimate there, and split and split and split near the pole. No matter how small the interval, the error estimate will still be large. This may lead to memory problems, for example.

Now, if your interval is _infinite_, the method first applies a transformation to a finite interval. This may already distort the function. Something to try is to limit the domain to finite values, especially since you know that your functions is virtually zero almost everywhere.

**Comment by OverLordGoldDragon** [comment]
`0.1, 100` - bingo. In fact `0, 100` works just fine too; since the non-zero region shifts based on `mu` I can also adapt the upper limit deterministically. Thank you for this explanation and overall responses.

**Comment by nschloe** [comment]
It'd not use `0, 100` -- If the integration code improves tomorrow, you'll get different values. Use `0.1, 100` to be on the safe side. (Always keep an eye on your function of course to make sure you don't cut off anything tangible.)

**Comment by OverLordGoldDragon** [comment]
Also I've no clue how practical this is but I'd think since the adaptive integration can work around the instability as you described for a finite interval like `0.1, 100`, it could also identify regions of instability and "devote more resources" to it rather than sample uniformly. Sure such a region could be anywhere from 0 to infinity but for that one could specify like `check_bounds=(0, 1000)`.

And right, I'll compare numbers exhaustively for my case to see if `0.1` misses out on something `0` doesn't.
